# markdown: redcarpet
# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "strikethrough"]

# highlighter: pygments

markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

highlighter: rouge

# baseurl: ""
baseurl: "/behaviac"
permalink: /:title/
excerpt_separator: ""


google_analytics_id: UA-11132649-2

# url: //www.behaviac.com
url: http://tencentopen.github.io

repository: https://github.com/TencentOpen/behaviac
help_url: https://github.com/TencentOpen/behaviac

collections:
  docs:
    output: true

name: behaviac Game AI, Behavior Tree, Finite State Machine, Hierarchical Task Network, BT FSM HTN
description: Advanced Game AI framework, Prototype Design, Client and Server, Unity 3D, Cocos2d-x, SDL and other game engine.


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: default
  -
    scope:
      path: _posts
      type: posts
    values:
      layout: default
  -
    scope:
      path: _posts/en
      type: posts
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fr
      type: posts
    values:
      layout: default
      lang: fr
  -
    scope:
      path: _posts/zh
      type: posts
    values:
      layout: default
      lang: zh
  -
    scope:
      path: zh
    values:
      lang: zh
  -
    scope:
      path: en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _docs/en
    values:
      layout: default
      lang: en
  - scope:
      path: _docs
    values:
      layout: default
      lang: zh

t:
  en:
    home:
      name: "Home"
      shortName: "Home"
      url: "/en/"
    docs:
      name: "Docs"
      shortName: "Docs"
      url: "/docs/en/articles/"
    references:
      name: "Ref<span class='hide-on-mobiles'>erence</span>s"
      shortName: "Refs"
      url: "/docs/en/references/"
    tutorials:
      name: "Tutor<span class='hide-on-mobiles'>ials</span>"
      shortName: "Tutor"
      url: "/docs/en/tutorials/"
    news:
      name: "Download"
    faq:
      name: "FAQ"
      url: "/en/faq/"
    help:
      name: "Help"
      url: "/en/help/"
    relatedPaper:
      name: "Related Paper"
    recentPaper: "Lastest Article"
    allIssues: "All Questions"
    lastIssues: "Lastest Issues"
    rss: "Feed"
    gotoTop: "Goto Top"
  zh:
    home:
      name: "首页"
      url: "/"
    docs:
      name: "文章"
      url: "/docs/zh/articles/"
    references:
      name: "手册"
      url: "/docs/zh/references/"
    tutorials:
      name: "教程"
      url: "/docs/zh/tutorials/"
    news:
      name: "下载"
    faq:
      name: "问答"
      url: "/zh/faq/"
    help:
      name: "帮助"
      url: "/zh/help/"
    relatedPaper:
      name: "相关资料"
    recentPaper: "最新文章"
    allIssues: "所有问题"
    lastIssues: "最新问题"
    rss: "订阅"
    gotoTop: "返回顶部"


